### ISSUE TITLE
USER STORIES - Account Registration

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#1]
EPIC: User - Account Registration

As a **User** I can **register** so that I **can use the site's services.**

**Acceptance Criteria**
- [x] User is able to set a username.
- [x] User is able to set a password.
- [x] Error message is shown in case the password or username entered is too short or invalid.

**Tasks**
- [x] Set username and password fields as required
- [x] Create sign up button
