### ISSUE TITLE
USER STORIES: Approve comments

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#10]
EPIC: Admin approved comments

As an **admin** I can **approve comments** so that I **can make sure inappropriate comments are censored.**

**Acceptance Criteria**
- [x] New comments are shown in admin page
- [x] Comments are displayed under a recipe upon admin approval

**Tasks**
- [x] Create Comment model
- [x] Create function that makes the comment visible after admin
- [x] Create action that enables the approving functionality for admin
