### ISSUE TITLE
USER STORIES: Contact Form

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#11]
EPIC: Contact form for registered and non-registered users

As a **registered/unregistered site user** I can **send a message** so that I **can share a recipe/ask a question/ask for help with an issue.**

**Acceptance Criteria**
- [x] A contact form requires the user to enter their name, email and message
- [x] User can't leave fields blank

**Tasks**
- [x] Create contact request with the requred fields
- [x] Set a success message for sending
- [x] Redirect the user to the contact page
