### ISSUE TITLE
USER STORIES - Login

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#2]
EPIC: User - Login

As a **User** I can **log in to my existing account** so that I **can view and manage my recipes.**

**Acceptance Criteria**
- [x] User can enter their previously created username and password and click a login button to log in.
- [x] After authentication, logout and add recipe, own recipe modification and deletion becomes available to the user.

**Tasks**
- [x] Create input fields: username and password
- [x] Login button that redirects user to home page
