### ISSUE TITLE
USER STORIES - Commenting

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#4]
EPIC: Commenting

As a **registered user** I can **approve comments** so that I **can make sure that inappropriate comments will be filtered out.**

**Acceptance Criteria**
- [x] Comments are only visible under a user's recipe once it's approved
- [x] Only an authorized user can comment
- [x] Approved comments are visible to the public
- [x] Display comment details: date and username

**Tasks**
- [x] Create comment model
- [x] Create comment form
- [x] Create admin approval function
