### ISSUE TITLE
USER STORIES: Rating

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#6]
EPIC: Rating

As a **User** I can **give rating to the recipes** so that I **and other users can see which recipes are the most popular.**

**Acceptance Criteria**
- [x] Only autenticated users can rate
- [x] Ratings should be visible both on the recipe card and the full detailed recipe page
- [x] Ratings don't need admin approval
- [x] The different levels should be represented with stars the user can choose from

**Tasks**
- [x] Create and average counter function for display
- [x] Create a radio button accompanied by the amount of stars (font awesome) that represent the users opinion
