### ISSUE TITLE
USER STORIES: Add recipe

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#7]
EPIC: Add user recipe

As a **user** I can **create a recipe** so that I **can widen the websites selection.**

**Acceptance Criteria**
- [x] The user can fill out a form with the recipe details
- [x] The user can upload an image for the recipe
- [x] When the user saves the recipe, it should appear both on the home and the recipes page
- [x] Only authenticated users can add their own recipe
- [x] Authenticated users don't need admin approval to save their recipe to the site

**Tasks**
- [x] Create a recipe form with the fields to be displayed
- [x] Create a request for adding a recipe using the previously created recipe form
- [x] Display a success or error message
- [x] Redirect the user to the add recipe page
