### ISSUE TITLE
USER STORIES: Delete recipe

### ISSUE THREAD

**Issue by vivienrauch** [vivienrauch/macromeals-pp4#9]
EPIC:  Authenticated user can delete own recipe

As a **user** I can **delete my recipe** so that I **can remove it if I don't want it to be displayed on the site anymore.**

**Acceptance Criteria**
- [x] User needs to be authenticated and
- [x] be the author of the recipe to be able to edit a recipe
- [x] The form should be rendered prefilled with the information that was previously saved

 create an UpdateView for the editing function
 tell it to use the edit recipe template and the recipe form

**Tasks**
- [x] create a DeleteView for the deletion function
- [x] tell it to use the edit recipe template and the recipe form
